GET http://localhost:3000/api/v1/tasks

###
GET http://localhost:3000/api/v1/tasks/61e53d2725b3e366acd2b816

###
POST http://localhost:3000/api/v1/tasks/get/evry
content-type: application/json

{
    "name": "meet a friend"
}

###

PATCH  http://localhost:3000/api/v1/tasks/61e07242d81ca65c80fea7e2
content-type: application/json

{
    "name": "create a new ",
    "completed": false
}
###

DELETE  http://localhost:3000/api/v1/tasks/61e23617ba0aa864ac925357
content-type: application/json



###
POST http://localhost:5000/api/v1/users/signup/verify
content-type: application/json

{
    
     "phoneNumber": "0971196736",
    "otp": "833260"
}
